### ISSUE TITLE
Team pictures 

### ISSUE THREAD

**Issue by mildaskl** [DefactoSoftware/LearningSpaces-Landing#100]
Steefs' name is on the Team part of the website, but instead of the picture you see a question mark. 
![screen shot 2016-05-31 at 14 59 10](https://cloud.githubusercontent.com/assets/8776552/15675054/55d5eb08-2740-11e6-9580-6e4e50d51d24.png)

**Comment by fatboypunk** [comment]
He can be removed right?

**Comment by RonaldDijkstra** [comment]
Yes, I did on the Defacto websites last monday.


Op 31 mei 2016 om 17:33 heeft Marcel Horlings <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


He can be removed right?

-

**Comment by mildaskl** [comment]
Yes, it can be removed. Right now it looks pretty bad on the website with that question mark.
