### ISSUE TITLE
Change parts on landing page LS

### ISSUE THREAD

**Issue by IwannaDJ** [DefactoSoftware/LearningSpaces-Landing#118]
Change parts on landing page www.learningspaces.io

Substitute text in header with:
All your learning activities in one place

Substitute text underneath animation and buttons with:
"LearningSpaces is your online learning community where you create and share knowledge. It makes the onboarding process easy and keeps expertise within your organization." 

Create three boxes under above text (in the white part of the page), put following texts in the boxes and create links to other pages:

### Small teams
We love small teams! For small teams, information is vital. LearningSpaces helps you keep your team's knowledge and experience in one place, so you can focus on growth and performance.

Following link on 'small teams' (first sentence)/ or somewhere something clickable to: http://www.learningspaces.io/small-teams/

### Large organizations
We have a lot of experience working with large organizations. Talking to key users, HR and management actually made us realize the time is right for 21st century corporate learning. With LearningSpaces setting up a corporate academy is easy and affordable

Following link on 'large organizations' (first sentence)/ or somewhere something clickable to: http://www.learningspaces.io/large-teams-and-organizations/

### Educators & Students
LearningSpaces is a solution that fits right into every educator’s needs. LearningSpaces' flexibility helps educators and students create content. Whether it's instructions, quizzes or assignments. Tailoring learning material to different needs hardly takes additional effort.

Following link on 'educators and students' (second sentence)/ or somewhere something clickable to: 
http://www.learningspaces.io/trainers-and-educators/

**Comment by fatboypunk** [comment]
> It makes the onboarding process easy, gets new colleagues up to speed in no time

These two trying to say the same thing

**Comment by IwannaDJ** [comment]
Edited.

**Comment by RonaldDijkstra** [comment]
Stongly advice to use 'learning activities' instead of 'learning efforts', because there's way more search volume on activities than on efforts: 

![learning-activities](https://cloud.githubusercontent.com/assets/16101007/19972068/49482e66-a1e1-11e6-9925-9bb7c9c27df0.png)

**Comment by fatboypunk** [comment]
> 'learning activities' instead of 'learning efforts',

But which of both will trigger people more?

**Comment by RonaldDijkstra** [comment]
Intent on both terms is really hard to predict.

**Comment by IwannaDJ** [comment]
Edited. With Ronald on this one. Let's try, see if it works or change it up later on (when we decide it doesn't work)?

**Comment by fatboypunk** [comment]
> Intent on both terms is really hard to predict.

Meh i think it helps just to figure out in what way your message gets to your users the best way instead of only taking volumes of search. And I don't agree with that you can't predict which message of 2 sentences comes across better.

**Comment by IwannaDJ** [comment]
What would be the best way to test it? Had a chat about it with Milda and we both thought activities could work really well.
