### ISSUE TITLE
Add pop up e-learning book English to www.learningspaces.io

### ISSUE THREAD

**Issue by IwannaDJ** [DefactoSoftware/LearningSpaces-Landing#122]
Add pop up e-book English on www.learningspaces.io

[Handboek Learn and let learn_Engels_v1.1_def_web.pdf](https://github.com/DefactoSoftware/LearningSpaces-Landing/files/571646/Handboek.Learn.and.let.learn_Engels_v1.1_def_web.pdf)

**Comment by sn3p** [comment]
I love the ebook but don't feel it on the LS website. Also I hate popups even though I created it on the Defacto website :P

**Comment by IwannaDJ** [comment]
Check, I also got the message that the landing page is best for creating trials instead of a pop as a marketing tool. True?

**Comment by fatboypunk** [comment]
> Check, I also got the message that the landing page is best for creating trials instead of a pop as a marketing tool.

guess that was me, but yeah i'd really would like everything on the home page to let the user get an account. Instead of being distracted for a book

**Comment by sn3p** [comment]
Ok let's close this for now.
