### ISSUE TITLE
Wide text on per team div

### ISSUE THREAD

**Issue by fatboypunk** [DefactoSoftware/LearningSpaces-Landing#126]
<img width="1251" alt="screen shot 2016-11-04 at 20 40 27" src="https://cloud.githubusercontent.com/assets/1089927/20019955/fd4464be-a2ce-11e6-9ba8-0ea4846577db.png">
it's around 127 chars

**Comment by fatboypunk** [comment]
Nobody told me to refresh :(

**Comment by RonaldDijkstra** [comment]
Thanks for checking, though

**Comment by fatboypunk** [comment]
haha <3
