### ISSUE TITLE
Add Google Analytics to Blog

### ISSUE THREAD

**Issue by sn3p** [DefactoSoftware/LearningSpaces-Landing#129]
@fatboypunk did we update the Ghost by any chance?
We are missing analytics since September :(

**Comment by fatboypunk** [comment]
Not sure, if you're an admin you can see if the analytics code is injected

**Comment by fatboypunk** [comment]
I think i can look into it today

**Comment by fatboypunk** [comment]
fixed

**Comment by sn3p** [comment]
thanks <3
