### ISSUE TITLE
Same Google Analytics ID for all languages

### ISSUE THREAD

**Issue by sn3p** [DefactoSoftware/LearningSpaces-Landing#13]
We now have the Same Google Analytics ID for all languages. Shouldn't we use a different ID's for all tld's? Just wondering... @romkebon ?

**Comment by jurre** [comment]
You can already differentiate them by tld so this way it's easier to see aggregated info imo

**Comment by matthijskuiper** [comment]
You can see the visitor's language, but I can't find which tld they visited. It just show's one `/` page.
Or am I looking at it the wrong way?

![screen shot 2015-02-07 at 13 18 15](https://cloud.githubusercontent.com/assets/935529/6092072/d5b3c3b6-aecb-11e4-8f86-9d6b6356e37e.png)

**Comment by jurre** [comment]
We're doing the same thing for our blog, it uses the same ID but we have a filter set up on `blog.learningspaces.io`

**Comment by romkebon** [comment]
Currently there's (as far as I know) no standard way to view this but you can use this segments:

https://www.google.com/analytics/web/template?uid=nOXBTHuZThqTpJr2m_kT1g (.io)
https://www.google.com/analytics/web/template?uid=NhFzWJbCRIKfcKBHkEsfdA (.nl)
https://www.google.com/analytics/web/template?uid=TWO5whJpRACaUzMZcVHACg (.de)

**Comment by matthijskuiper** [comment]
Works great, thanks
