### ISSUE TITLE
Update footer

### ISSUE THREAD

**Issue by fatboypunk** [DefactoSoftware/LearningSpaces-Landing#139]
<img width="157" alt="screen shot 2017-01-03 at 13 52 28" src="https://cloud.githubusercontent.com/assets/1089927/21608305/f38ed1e0-d1bb-11e6-9128-e8ce68d57790.png">

**Comment by sn3p** [comment]
Will be updated on next build/deploy 👍

**Comment by sn3p** [comment]
Done 🎉
