### ISSUE TITLE
Request A Demo

### ISSUE THREAD

**Issue by fatboypunk** [DefactoSoftware/LearningSpaces-Landing#141]
So lately i've come across multiple sites where they only offer demo's which I never use because that means i have to talk to people while i actually want to figure it out myself. But in trials we do get people asking for these things.

**step 1:** To offer this we could just stick with a typeform thingy where we ask everything we need to set it up properly and ask for a number/skype to make a call. Since this can be done next to start your own trial that asks less i think it's doable to ask for more.

(Now the following bit is a bit more work but in the end i think it would pay of and eventually we could automate it)

**step 2:** Setup a call for in about 3 days(?)

**Step 3:** Setup a team/enviroment/tenant space:
* if they're marketing orientated we could tailor it to that
* if they're more into selling coffee we could make spaces and paths in that area
* etc, you get the point

But all can have the onboarding this company spaces and paths.

**step 3:** now we can call/skype them walk them through how they could use it tell them some other stuff they didn't know already give them some more info afterwards and convert them

**Comment by RonaldDijkstra** [comment]
Sounds promising

**Comment by sn3p** [comment]
Yea sounds good, did something similar for zerocopter: https://zerocopter.com/request-demo/
