### ISSUE TITLE
Dutch translation in en.yml

### ISSUE THREAD

**Issue by sn3p** [DefactoSoftware/LearningSpaces-Landing#59]
**[en.yml#L235-L249](https://github.com/DefactoSoftware/LearningSpaces-Landing/blob/master/locales/en.yml#L235-L249)**

<img src="https://s3-eu-west-1.amazonaws.com/uploads-eu.hipchat.com/75656/630027/sQ8XFpV3jEtRLFS/Screen%20Shot%202016-01-29%20at%2013.56.23.png">

**Comment by fatboypunk** [comment]
#61

**Comment by sn3p** [comment]
@isabelamy I translated the Dutch answer, what do you think? Feel free to edit!

> With LearningSpaces it's up to you who can access your content. Only people who register and log in have access, and **you are in control** of who is allowed to.
>   
> This means you could keep registrations **open for everyone**, which basically makes it a public community.
> 
> Or grant people access based on email rules. For example only allow users with an email address ending with `@mycompany.com` to register or log in.
> 
> It’s also possible to completely restrict access, and only grant access to people by sending them an invite from LearningSpaces.
