### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by sn3p** [DefactoSoftware/LearningSpaces-Landing#69]
I've added all German translations (https://github.com/DefactoSoftware/LearningSpaces-Landing/pull/68).
We still need a few more:

In **NL** and **DE**, preferably including `Focus`:
```
Focus your team’s learning efforts
```

In **DE**:
```
Please enter your team’s LearningSpaces domain
Could not find that domain.
Continue
Trying to set up LearningSpaces for your team?
```

@isabelamy can you give this a shot when you have the time?

**Comment by isabelamy** [comment]
Bitte gebe die Domain von deinem Team an
Die Domain konnte nicht gefunden werden.
Weiter
Willst du LearningSpaces für dein Team einrichten?

@sn3p
